/*
 * File: app/store/Histories.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CT.store.Histories', {
    extend: 'Ext.data.Store',

    requires: [
        'CT.model.History',
        'Ext.data.proxy.LocalStorage'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Histories',
            autoLoad: true,
            model: 'CT.model.History',
            proxy: {
                type: 'localstorage',
                id: 'chat-histories'
            }
        }, cfg)]);
    }
});