/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CT.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'CT.view.MyViewportViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.panel.Tool'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            layout: 'border',
            title: 'CHROME TALK <i class="fa fa-comments"></i>',
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    cls: 'display-panel',
                    id: 'displayPanel'
                },
                {
                    xtype: 'form',
                    flex: 1,
                    region: 'south',
                    split: true,
                    height: 150,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '10em',
                            fieldLabel: '<i class="fa fa-search"></i> Google Account',
                            labelWidth: 150,
                            emptyText: 'example@gmail.com'
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'connectButton',
                                    margin: '0 10em 10em',
                                    text: '<i class="fa fa-video-camera"></i> CONNECT'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            margin: '10em',
                            minHeight: 100,
                            title: '<i class="fa fa-list-alt"></i> CONTACTS',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    margin: '10em',
                                    minHeight: 100,
                                    title: '',
                                    hideHeaders: true,
                                    store: 'Histories',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'address',
                                            text: 'String',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            tools: [
                {
                    xtype: 'tool'
                }
            ]
        }
    ]

});